<?php
function addition($temp){
	$bbcode = array(
		"#\[image:(0-9)\]#is",
		"#\[video:(0-9)\]#is",
	);

	$replacement = array(
		"Image No : \\1",
		"Video No : \\1",
	);

	$temp = preg_replace ($bbcode,$replacement,$temp);

	return $temp;
}

function data($temp,$show = 1,$html = false) {

		$temp = eregi_replace ( "\[left\]|\[l\]", "<p align=\"left\">" , $temp ) ;
		$temp = eregi_replace ( "\[/left\]|\[/l\]", "</p>" , $temp ) ;
		$temp = eregi_replace ( "\[center\]|\[c\]", "<p align=\"center\">" , $temp ) ;
		$temp = eregi_replace ( "\[/center\]|\[/c\]", "</p>" , $temp ) ;
		$temp = eregi_replace ( "\[right\]|\[r\]", "<p align=\"right\">" , $temp ) ;
		$temp = eregi_replace ( "\[/right\]|\[/r\]", "</p>" , $temp ) ;
	
		$temp = eregi_replace ( "\[b\]", "<b>" , $temp ) ;
		$temp = eregi_replace ( "\[/b\]", "</b>" , $temp ) ;
		$temp = eregi_replace ( "\[i\]", "<i>" , $temp ) ;
		$temp = eregi_replace ( "\[/i\]", "</i>" , $temp ) ;
		$temp = eregi_replace ( "\[u\]", "<u>" , $temp ) ;
		$temp = eregi_replace ( "\[/u\]", "</u>" , $temp ) ;
		$temp = eregi_replace ( "\[color=(\#[0-9A-F]{6}|[a-z]+)\]", "<font color=\"\\1\">" , $temp ) ;
		$temp = eregi_replace ( "\[/color\]|\[/size\]", "</font>" , $temp ) ;
		$temp = eregi_replace ( "\[size=([0-9])\]", "<font size=\"\\1pt\">" , $temp ) ;

	//if ($show == 1){ $img_tag = "<img src=\"\\1\" border=\"0\">"; } else { $img_tag = "<a href=\"\\1\" target=\"_blank\">\\1</a>"; }

	$bbcode = array(
		"#\[img\]([^?].*?)\[/img\]#i",
		"#\[img=([^?].*?)\]([^?].*?)\[/img\]#i",
		"#\[url\]([\w]+?://([\w\#$%&~/.\-;:=,?@\]+]|\[(?!url=))*?)\[/url\]#is",
		"#\[url\]((www|ftp)\.([\w\#$%&~/.\-;:=,?@\]+]|\[(?!url=))*?)\[/url\]#is",
		"#\[url=([\w]+?://[\w\#$%&~/.\-;:=,?@\[\]+]*?)\]([^?\n\r\t].*?)\[/url\]#is",
		"#\[url=((www|ftp)\.[\w\#$%&~/.\-;:=,?@\[\]+]*?)\]([^?\n\r\t].*?)\[/url\]#is",
		"#\[a=([\w]+?://[\w\#$%&~/.\-;:=,?@\[\]+]*?)\]([^?\n\r\t].*?)\[/a\]#is",
		"#\[a=((www|ftp)\.[\w\#$%&~/.\-;:=,?@\[\]+]*?)\]([^?\n\r\t].*?)\[/a\]#is",
		"#\[qoute=([^?].*?)\]([^?].*?)\[/qoute\]#is",
		"#\[qoute\]([^?].*?)\[/qoute\]#is",
	);

	$replacement = array(
		"<img src=\"\\1\" border=\"0\">",
		"<a href=\"". FULL_URL ."/gallery/image.php?id=\\1\" target=\"_blank\"><img src=\"\\2\" border=\"0\"></a>",
		"<a href=\"\\1\" target=\"_blank\">\\1</a>",
		"<a href=\"http://\\1\" target=\"_blank\">\\1</a>",
		"<a href=\"\\1\" target=\"_blank\">\\2</a>",
		"<a href=\"http://\\1\" target=\"_blank\">\\3</a>",
		"<a href=\"\\1\" target=\"_blank\">\\2</a>",
		"<a href=\"http://\\1\" target=\"_blank\">\\3</a>",
		"<br><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"><tr><td>
			<fieldset style=\"border: 1px solid \#D3D3D3; padding: 2px; \">
			<legend><b>Quote</b> \\1</legend>
			\\2</fieldset></td><td width=\"120\">&nbsp;</td></tr></table>",
		"<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"style1\"><tr><td>
			<fieldset style=\"border: 1px solid \#D3D3D3; padding: 2px; \">
			<legend><b>Quote</b></legend>
			\\1</fieldset></td><td width=\"120\">&nbsp;</td></tr></table>"
	);

	$temp = preg_replace ($bbcode,$replacement,$temp);

	if ($html){		$temp = html_entity_decode($temp);	}

	$temp = eregi_replace ( "\[p\]", "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" , $temp ) ;

	return $temp;
}

function emoticon($temp){

	$img = " <img border=\"0\" src=\"../images/e";

	$emoticon = array(
		 " :)",
	 " :D",
	 " :(",
	 " (H)",
	 " :P",
	 " :|",
	 " ;)",
	 " :o",
	 " :$",
	 " :s",
	 " :'(",
	 " (A)",
	 " |-o",
	 " &lt;:-)",
	 " 8|",
	 " ^o)",
	 " :-*",
	 " +:(",
	 " 8o|",
	 " :-#",
	 " 8-|",
	 " :@",
	 " #;)",
	 " #D",
	 " #,",
	 " #P",
	 " #)",
	 " #(H)",
	 " #:P",
	 " #$",
	 " #i",
	 " #(",
	 " #p",
	 " #X",
	 " #_",
	 " #z",
	 " #o",
	 " #i",
	 " #:p",
	 " #^^",
	 " #OO",
	 " #|",
	 " #:|",
	 " (L)",
	 " (U)",
	 " #01#",
	 " #02#",
	 " #03#",
	 " #04#",
	 " #05#",
	 " #06#",
	 " #07#",
	 " #08#",
	 " #09#",
	 " #10#", 
	 " #11#", 
	 " #12#", 
	 " #13#", 
	 " #14#", 
	 " #15#", 
	 " #16#", 
	 " #17#", 
	 " #18#", 
	 " #19#", 
	 " #20#", 
	 " #21#", 
	 " #22#", 
	 " #23#", 
	 " #24#", 
	 " #25#",
	 " #26#", 
	 " #27#",
	 " #28#",
	 "/me ",
	 " T_T",
	 " (6)",
	 " O_O",
	 " (z)",
	 " - -;",
	 " (y)",
	 " (n)",
	 " (!)",
	 " (?)",
	 " (*)",
		" (o01)",
		" (o02)",
		" (o03)",
		" (o04)",
		" (o05)",
		" (o06)",
		" (o07)",
		" (o08)",
		" (o09)",
		" (o10)",
		" (o11)",
		" (o12)",
		" (o13)",
		" (o14)",
		" (o15)",
		" (o16)",
		" (o17)",
		" (o18)",
		" (o19)",
		" (o20)",
		" (o21)",
		" (o22)",
		" (o23)",
		" (o24)",
		" (o25)",
		" (o26)",
		" (o27)",
		" (o28)",
		" (o29)",
		" (o30)",
		" (o31)",
		" (o32)",
		" (o33)",
		" (o34)",
		" (o35)",
		" (o36)",
		" (o37)",
		" (o38)",
		" (o39)",
		" (o40)",
		" (o41)",
		" (o42)",
		" (o43)",
		" (o44)",
		" (o45)",
		" (o46)",
		" (o47)",
		" (o48)",
		" (o49)",
		" (o50)",
		" (o51)",
		" (o52)",
		" (o53)",
		" (o54)",
		" (o55)",
		" (o56)",
		" (o57)",
		" (o58)",
		" (o59)",
		" (o60)",
		" (o61)",
		" (o62)",
		" (o63)",
		" (o64)",
		" (o65)",
		" (o66)",
		" (o67)",
		" (o68)",
		" (o69)",
		" (o70)",
		" (o71)",
		" (o72)",
		" (y01)",
		" (y02)",
		" (y03)",
		" (y04)",
		" (y05)",
		" (y06)",
		" (y07)",
		" (y08)",
		" (y09)",
		" (y10)",
		" (y11)",
		" (y12)",
		" (y13)",
		" (y14)",
		" (y15)",
		" (y16)",
		" (y17)",
		" (y18)",
		" (y19)",
		" (y20)",
		" (y21)",
		" (y22)",
		" (y23)",
		" (y24)",
		" (y25)",
		" (y26)",
		" (y27)",
		" (y28)",
		" (y29)",
		" (y30)",
		" (y31)",
		" (y32)",
		" (y33)",
		" (y34)",
		" (y35)",
		" (y36)",
		" (y37)",
		" (y38)",
		" (y39)",
		" (y40)",
		" (y41)",
		" (y42)",
		" (y43)",
		" (y44)",
		" (y45)",
		" (y46)",
		" (y47)",
		" (y48)",
		" (y49)",
		" (y50)",
		" (y51)",
		" (y52)",
		" (y53)",
		" (y54)",
		" (y55)",
		" (emo1)",
		" (emo2)",
		" (emo3)",
		" (emo4)",
		" (emo5)",
		" (emo6)",
		" (emo7)",
		" (emo8)",
		" (emo9)",
		" (emo10)",
		" (emo11)"
		);

	$replacement = array(
		$img."/regular_smile.gif\">" ,
		$img."/teeth_smile.gif\">" ,
		$img."/sad_smile.gif\">" ,
		$img."/shades_smile.gif\">" ,
		$img."/tongue_smile.gif\">" ,
		$img."/what_smile.gif\">" ,
		$img."/wink_smile.gif\">" ,
		$img."/omg_smile.gif\">" ,
		$img."/red_smile.gif\">" ,
		$img."/confused_smile.gif\">" ,
		$img."/cry_smile.gif\">" ,
		$img."/angel_smile.gif\">" ,
		$img."/77_77.gif\">" ,
		$img."/74_74.gif\">" ,
		$img."/71_71.gif\">" ,
		$img."/50_50.gif\">" ,
		$img."/51_51.gif\">" ,
		$img."/52_52.gif\">" ,
		$img."/48_48.gif\">" ,
		$img."/47_47.gif\">" ,
		$img."/49_49.gif\">" ,
		$img."/angry_smile.gif\">" ,
		$img."/1902ok.gif\">" ,
		$img."/77.gif\">" ,
		$img."/71_71.gif\">" ,
		$img."/p.gif\">" ,
		$img."/Cara_8.gif\">" ,
		$img."/Emo_2.gif\">" ,
		$img."/Emo_4.gif\">" ,
		$img."/Emo_9.gif\">" ,
		$img."/Emo_5.gif\">" ,
		$img."/Emo_21.gif\">" ,
		$img."/Emo_33.gif\">" ,
		$img."/Emo_68.gif\">" ,
		$img."/Emo_73.gif\">" ,
		$img."/Emo_75.gif\">" ,
		$img."/Emo_85.gif\">" ,
		$img."/Emo_89.gif\">" ,
		$img."/EmpPack3_95.gif\">" ,
		$img."/EmpPack3_35.gif\">" ,
		$img."/EmpPack3_86.gif\">" ,
		$img."/Teeth_Smiley.gif\">" ,
		$img."/EmpPack3_92.gif\">" ,
		$img."/heart.gif\">" ,
		$img."/broken_heart.gif\">" ,
		$img."/57_57.gif\">" ,
		$img."/58_58.gif\">" ,
		$img."/59_59.gif\">" ,
		$img."/60_60.gif\">" ,
		$img."/61_61.gif\">" ,
		$img."/62_62.gif\">" ,
		$img."/63_63.gif\">" ,
		$img."/64_64.gif\">" ,
		$img."/66_66.gif\">" ,
		$img."/69_69.gif\">" ,
		$img."/73_73.gif\">" ,
		$img."/bat.gif\">" ,
		$img."/beer_mug.gif\">" ,
		$img."/rose.gif\">" ,
		$img."/wilted_rose.gif\">" ,
		$img."/camera.gif\">" ,
		$img."/cat.gif\">" ,
		$img."/clock.gif\">" ,
		$img."/coffee.gif\">" ,
		$img."/dog.gif\">" ,
		$img."/cake.gif\">" ,
		$img."/envelope.gif\">" ,
		$img."/film.gif\">" ,
		$img."/messenger.gif\">" ,
		$img."/moon.gif\">" ,
		$img."/note.gif\">" ,
		$img."/phone.gif\">" ,
		$img."/present.gif\">" ,
		$img."/action.gif\"> " ,
		$img."/1.gif\">" ,
		$img."/devil_smile.gif\">" ,
		$img."/3_86.gif\">" ,
		$img."/Emo_75.gif\">" ,
		$img."/Emo_5.gif\">" ,
		$img."/thumbs_up.gif\">" ,
		$img."/thumbs_down.gif\">" ,
		$img."/emo160.gif\">" ,
		$img."/emo159.gif\">" ,
		$img."/star.gif\">" ,
		$img."/o01.gif\">" , // Onion 1
		$img."/o02.gif\">" ,
		$img."/o03.gif\">" ,
		$img."/o04.gif\">" ,
		$img."/o05.gif\">" ,
		$img."/o06.gif\">" ,
		$img."/o07.gif\">" ,
		$img."/o08.gif\">" ,
		$img."/o09.gif\">" ,
		$img."/o10.gif\">" ,
		$img."/o11.gif\">" ,
		$img."/o12.gif\">" ,
		$img."/o13.gif\">" ,
		$img."/o14.gif\">" ,
		$img."/o15.gif\">" ,
		$img."/o16.gif\">" ,
		$img."/o17.gif\">" ,
		$img."/o18.gif\">" ,
		$img."/o19.gif\">" ,
		$img."/o20.gif\">" ,
		$img."/o21.gif\">" ,
		$img."/o22.gif\">" ,
		$img."/o23.gif\">" ,
		$img."/o24.gif\">" ,
		$img."/o25.gif\">" ,
		$img."/o26.gif\">" ,
		$img."/o27.gif\">" ,
		$img."/o28.gif\">" ,
		$img."/o29.gif\">" ,
		$img."/o30.gif\">" ,
		$img."/o31.gif\">" ,
		$img."/o32.gif\">" ,
		$img."/o33.gif\">" ,
		$img."/o34.gif\">" ,
		$img."/o35.gif\">" ,
		$img."/o36.gif\">" ,
		$img."/o37.gif\">" ,
		$img."/o38.gif\">" ,
		$img."/o39.gif\">" ,
		$img."/o40.gif\">" ,
		$img."/o41.gif\">" ,
		$img."/o42.gif\">" ,
		$img."/o43.gif\">" ,
		$img."/o44.gif\">" ,
		$img."/o45.gif\">" ,
		$img."/o46.gif\">" ,
		$img."/o47.gif\">" ,
		$img."/o48.gif\">" ,
		$img."/o49.gif\">" ,
		$img."/o50.gif\">" ,
		$img."/o51.gif\">" ,
		$img."/o52.gif\">" ,
		$img."/o53.gif\">" ,
		$img."/o54.gif\">" ,
		$img."/o55.gif\">" ,
		$img."/o56.gif\">" ,
		$img."/o57.gif\">" ,
		$img."/o58.gif\">" ,
		$img."/o59.gif\">" ,
		$img."/o60.gif\">" ,
		$img."/o61.gif\">" ,
		$img."/o62.gif\">" ,
		$img."/o63.gif\">" ,
		$img."/o64.gif\">" ,
		$img."/o65.gif\">" ,
		$img."/o66.gif\">" ,
		$img."/o67.gif\">" ,
		$img."/o68.gif\">" ,
		$img."/o69.gif\">" ,
		$img."/o70.gif\">" ,
		$img."/o71.gif\">" ,
		$img."/o72.gif\">" ,
		$img."/y01.gif\">" ,
		$img."/y02.gif\">" ,
		$img."/y03.gif\">" ,
		$img."/y04.gif\">" ,
		$img."/y05.gif\">" ,
		$img."/y06.gif\">" ,
		$img."/y07.gif\">" ,
		$img."/y08.gif\">" ,
		$img."/y09.gif\">" ,
		$img."/y10.gif\">" ,
		$img."/y11.gif\">" ,
		$img."/y12.gif\">" ,
		$img."/y13.gif\">" ,
		$img."/y14.gif\">" ,
		$img."/y15.gif\">" ,
		$img."/y16.gif\">" ,
		$img."/y17.gif\">" ,
		$img."/y18.gif\">" ,
		$img."/y19.gif\">" ,
		$img."/y20.gif\">" ,
		$img."/y21.gif\">" ,
		$img."/y22.gif\">" ,
		$img."/y23.gif\">" ,
		$img."/y24.gif\">" ,
		$img."/y25.gif\">" ,
		$img."/y26.gif\">" ,
		$img."/y27.gif\">" ,
		$img."/y28.gif\">" ,
		$img."/y29.gif\">" ,
		$img."/y30.gif\">" ,
		$img."/y31.gif\">" ,
		$img."/y32.gif\">" ,
		$img."/y33.gif\">" ,
		$img."/y34.gif\">" ,
		$img."/y35.gif\">" ,
		$img."/y36.gif\">" ,
		$img."/y37.gif\">" ,
		$img."/y38.gif\">" ,
		$img."/y39.gif\">" ,
		$img."/y40.gif\">" ,
		$img."/y41.gif\">" ,
		$img."/y42.gif\">" ,
		$img."/y43.gif\">" ,
		$img."/y44.gif\">" ,
		$img."/y45.gif\">" ,
		$img."/y46.gif\">" ,
		$img."/y47.gif\">" ,
		$img."/y48.gif\">" ,
		$img."/y49.gif\">" ,
		$img."/y50.gif\">" ,
		$img."/y51.gif\">" ,
		$img."/y52.gif\">" ,
		$img."/y53.gif\">" ,
		$img."/y54.gif\">" ,
		$img."/y55.gif\">" ,
		$img."/emo1.gif\">" ,
		$img."/emo2.gif\">" ,
		$img."/emo3.gif\">" ,
		$img."/emo4.gif\">" ,
		$img."/emo5.gif\">" ,
		$img."/emo6.gif\">" ,
		$img."/emo7.gif\">" ,
		$img."/emo8.gif\">" ,
		$img."/emo9.gif\">" ,
		$img."/emo10.gif\">" ,
		$img."/emo11.gif\">" ,
	);
	$temp = str_replace ( $emoticon , $replacement , $temp ) ;

return $temp;
}

function data_view($data){
	return emoticon(data(clear_line($data)));
}

function news_view($data){
	return emoticon(data(clear_line($data),1,true));
}

function clear_line($text) {
  $text = htmlspecialchars($text);
  $text = ereg_replace("\n", "<br>", $text);
  $text = ereg_replace("\r", "", $text);
  return $text;
}

?>